### PR TITLE
Fix CSS for 2.0 final

### PR DESCRIPTION
**Pull request by srijken**
Fixes issue #3

### CODE REVIEW

**Review by zliebersbach — APPROVED** [review]

**Comment by srijken** [comment]
Apparently it doesn't close the PR when the CI fails. Any idea why that fails?

**Comment by zliebersbach** [comment]
@srijken Nope, no idea. I don't have the time to look into this now, but if you find a solution I'm happy to implement it.

**Comment by srijken** [comment]
@wincinderith Fixed the build :)

**Comment by zliebersbach** [comment]
@srijken Woo! :tada:

**Pull request merged**
